

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const dados = "https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"
    return (
    <html lang="en">
      <head> 
        {/* <Script 
          strategy="beforeInteractive"        
          src={dados}
          /> */}
 </head>
      <body className=' mt-0 w-screen lg:h-[3500px]  h-[3800px] 
       bg-center bg-no-repeat bg-zinc-950 overflow-x-hidden'>
        {children}
        </body>
    </html>
  );
}
